import { iconUrl } from '@/lib/logo-icons';
import type { BackgroundConfig, LogoLayer } from '../LogoMaker';

export interface LogoTemplate {
	id: string;
	name: string;
	layers: LogoLayer[];
	background: BackgroundConfig;
}

export const logoTemplates: LogoTemplate[] = [
	{
		id: 'instagram-sunset',
		name: 'Instagram Sunset',
		background: {
			type: 'gradient',
			solidColor: '#e1306c',
			gradientColors: ['#833ab4', '#fd1d1d', '#fcb045'],
			gradientDirection: 'to top right',
			noise: 0,
			borderRadius: 60,
			pattern: 'none',
			patternColor: '#ffffff',
			patternOpacity: 0.1,
			shape: 'squircle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-instagram',
				iconName: 'ri:instagram-fill',
				url: iconUrl('ri:instagram-fill'),
				x: 256,
				y: 256,
				scale: 1.7,
				rotation: 0,
				fill: '#ffffff',
				stroke: 'none',
				overwriteFill: true,
				overwriteStroke: false,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#833ab4',
				shadowBlur: 20,
				shadowOffsetX: 0,
				shadowOffsetY: 8,
				shadowOpacity: 0.35,
			},
		],
	},
	{
		id: 'facebook-brand',
		name: 'Facebook Royal Blue',
		background: {
			type: 'gradient',
			solidColor: '#1877f2',
			gradientColors: ['#1877f2', '#0866ff'],
			gradientDirection: 'to bottom',
			noise: 0,
			borderRadius: 100,
			pattern: 'none',
			patternColor: '#ffffff',
			patternOpacity: 0.1,
			shape: 'circle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-facebook',
				iconName: 'ri:facebook-fill',
				url: iconUrl('ri:facebook-fill'),
				x: 256,
				y: 275,
				scale: 2.1,
				rotation: 0,
				fill: '#ffffff',
				stroke: 'none',
				overwriteFill: true,
				overwriteStroke: false,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#000000',
				shadowBlur: 18,
				shadowOffsetX: 0,
				shadowOffsetY: 8,
				shadowOpacity: 0.28,
			},
		],
	},
	{
		id: 'spotify-neon',
		name: 'Spotify Midnight Neon',
		background: {
			type: 'gradient',
			solidColor: '#121212',
			gradientColors: ['#191414', '#121212'],
			gradientDirection: 'to bottom',
			noise: 0,
			borderRadius: 100,
			pattern: 'none',
			patternColor: '#1ed760',
			patternOpacity: 0.1,
			shape: 'circle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-spotify',
				iconName: 'ri:spotify-fill',
				url: iconUrl('ri:spotify-fill'),
				x: 256,
				y: 256,
				scale: 1.8,
				rotation: 0,
				fill: '#1ed760',
				stroke: 'none',
				overwriteFill: true,
				overwriteStroke: false,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#1ed760',
				shadowBlur: 24,
				shadowOffsetX: 0,
				shadowOffsetY: 0,
				shadowOpacity: 0.5,
			},
		],
	},
	{
		id: 'supabase-emerald',
		name: 'Supabase Emerald Glow',
		background: {
			type: 'gradient',
			solidColor: '#1c1c1c',
			gradientColors: ['#242424', '#121212'],
			gradientDirection: 'to bottom right',
			noise: 0,
			borderRadius: 60,
			pattern: 'none',
			patternColor: '#3ecf8e',
			patternOpacity: 0.1,
			shape: 'squircle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-supabase',
				iconName: 'simple-icons:supabase',
				url: iconUrl('simple-icons:supabase'),
				x: 256,
				y: 256,
				scale: 1.8,
				rotation: 0,
				fill: '#3ecf8e',
				stroke: 'none',
				overwriteFill: true,
				overwriteStroke: false,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#3ecf8e',
				shadowBlur: 26,
				shadowOffsetX: 0,
				shadowOffsetY: 0,
				shadowOpacity: 0.6,
			},
		],
	},
	{
		id: 'stripe-violet',
		name: 'Stripe Indigo Mesh',
		background: {
			type: 'gradient',
			solidColor: '#635bff',
			gradientColors: ['#635bff', '#7a73ff', '#0a2540'],
			gradientDirection: 'to bottom right',
			noise: 0,
			borderRadius: 60,
			pattern: 'none',
			patternColor: '#ffffff',
			patternOpacity: 0.1,
			shape: 'squircle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-stripe',
				iconName: 'simple-icons:stripe',
				url: iconUrl('simple-icons:stripe'),
				x: 256,
				y: 256,
				scale: 1.7,
				rotation: 0,
				fill: '#ffffff',
				stroke: 'none',
				overwriteFill: true,
				overwriteStroke: false,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#635bff',
				shadowBlur: 22,
				shadowOffsetX: 0,
				shadowOffsetY: 8,
				shadowOpacity: 0.4,
			},
		],
	},
	{
		id: 'linear-obsidian',
		name: 'Linear Obsidian Violet',
		background: {
			type: 'gradient',
			solidColor: '#181924',
			gradientColors: ['#1c1d2d', '#0f1017'],
			gradientDirection: 'to bottom',
			noise: 0,
			borderRadius: 60,
			pattern: 'grid',
			patternColor: '#5e6ad2',
			patternOpacity: 0.15,
			shape: 'squircle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-linear',
				iconName: 'simple-icons:linear',
				url: iconUrl('simple-icons:linear'),
				x: 256,
				y: 256,
				scale: 1.75,
				rotation: 0,
				fill: '#5e6ad2',
				stroke: 'none',
				overwriteFill: true,
				overwriteStroke: false,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#5e6ad2',
				shadowBlur: 22,
				shadowOffsetX: 0,
				shadowOffsetY: 6,
				shadowOpacity: 0.45,
			},
		],
	},
	{
		id: 'modern-lightning',
		name: 'Modern Lightning Badge',
		background: {
			type: 'gradient',
			solidColor: '#4f46e5',
			gradientColors: ['#4f46e5', '#7c3aed', '#db2777'],
			gradientDirection: 'to bottom right',
			noise: 0.03,
			borderRadius: 60,
			pattern: 'none',
			patternColor: '#ffffff',
			patternOpacity: 0.15,
			shape: 'squircle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-lightning',
				iconName: 'solar:bolt-bold-duotone',
				url: iconUrl('solar:bolt-bold-duotone'),
				x: 256,
				y: 256,
				scale: 1.9,
				rotation: 0,
				fill: '#ffffff',
				stroke: 'none',
				overwriteFill: true,
				overwriteStroke: false,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#000000',
				shadowBlur: 24,
				shadowOffsetX: 0,
				shadowOffsetY: 10,
				shadowOpacity: 0.4,
			},
		],
	},
	{
		id: 'blueprint-grid',
		name: 'Blueprint Grid',
		background: {
			type: 'solid',
			solidColor: '#0d47a1',
			gradientColors: [],
			gradientDirection: 'to right',
			noise: 0,
			borderRadius: 0,
			pattern: 'grid',
			patternColor: '#ffffff',
			patternOpacity: 0.2,
			shape: 'rectangle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-blueprint',
				iconName: 'lucide:ruler',
				url: 'https://api.iconify.design/lucide/ruler.svg',
				x: 256,
				y: 256,
				scale: 1.2,
				rotation: -45,
				fill: 'none',
				stroke: '#ffffff',
				overwriteFill: false,
				overwriteStroke: true,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#000000',
				shadowBlur: 5,
				shadowOffsetX: 2,
				shadowOffsetY: 2,
				shadowOpacity: 0.3,
			},
		],
	},
	{
		id: 'app-icon-squircle',
		name: 'App Icon',
		background: {
			type: 'gradient',
			solidColor: '#ffffff',
			gradientColors: ['#a8ff78', '#78ffd6'],
			gradientDirection: 'to bottom right',
			noise: 0,
			borderRadius: 0,
			pattern: 'dots',
			patternColor: '#ffffff',
			patternOpacity: 0.3,
			shape: 'squircle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-app',
				iconName: 'solar:smile-circle-bold',
				url: iconUrl('solar:smile-circle-bold'),
				x: 256,
				y: 256,
				scale: 1.4,
				rotation: 0,
				fill: '#ffffff',
				stroke: 'none',
				overwriteFill: true,
				overwriteStroke: false,
				opacity: 0.8,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#ffffff',
				shadowBlur: 0,
				shadowOffsetX: 0,
				shadowOffsetY: 0,
				shadowOpacity: 0,
			},
		],
	},
	{
		id: 'eco-friendly',
		name: 'Eco Friendly',
		background: {
			type: 'gradient', // Switched to gradient
			solidColor: '#e6f4ea',
			gradientColors: ['#a8e063', '#56ab2f'], // Fresh green gradient
			gradientDirection: 'to top right',
			noise: 0.05,
			borderRadius: 256,
			pattern: 'none',
			patternColor: '#000000',
			patternOpacity: 0.1,
			shape: 'rectangle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-2',
				iconName: 'lucide:leaf',
				url: 'https://api.iconify.design/lucide/leaf.svg',
				x: 256,
				y: 256,
				scale: 1.1,
				rotation: 0,
				fill: '#ffffff', // White icon stands out on green
				stroke: 'none',
				overwriteFill: true,
				overwriteStroke: false,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#56ab2f',
				shadowBlur: 10,
				shadowOffsetX: 2,
				shadowOffsetY: 4,
				shadowOpacity: 0.3,
			},
		],
	},
	{
		id: 'fitness-gym',
		name: 'Fitness Gym',
		background: {
			type: 'solid',
			solidColor: '#e7e7e7',
			gradientColors: ['#232526', '#414345'], // Dark metal look
			gradientDirection: 'to bottom right',
			noise: 0.05,
			borderRadius: 100, // Circle
			pattern: 'grid', // Mesh look
			patternColor: '#ffffff',
			patternOpacity: 0.5,
			shape: 'rectangle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-dumbbell',
				iconName: 'lucide:dumbbell',
				url: 'https://api.iconify.design/lucide/dumbbell.svg',
				x: 256,
				y: 256,
				scale: 1.5,
				rotation: 45,
				fill: 'none',
				stroke: '#ff4b1f', // Hot red/orange
				overwriteFill: false,
				overwriteStroke: true,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#ff4b1f',
				shadowBlur: 15,
				shadowOffsetX: 0,
				shadowOffsetY: 0,
				shadowOpacity: 0,
			},
		],
	},
	{
		id: 'pet-care',
		name: 'Pet Care',
		background: {
			type: 'solid',
			solidColor: '#fff3e0',
			gradientColors: [],
			gradientDirection: 'to right',
			noise: 0,
			borderRadius: 60,
			pattern: 'none',
			patternColor: '#000000',
			patternOpacity: 0.1,
			shape: 'rectangle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-paw',
				iconName: 'lucide:paw-print',
				url: 'https://api.iconify.design/lucide/paw-print.svg',
				x: 256,
				y: 256,
				scale: 1.0,
				rotation: 0,
				fill: '#ff9800',
				stroke: 'none',
				overwriteFill: true,
				overwriteStroke: false,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#ff9800',
				shadowBlur: 0,
				shadowOffsetX: 0,
				shadowOffsetY: 0,
				shadowOpacity: 0,
			},
		],
	},
	{
		id: 'tech-startup',
		name: 'Tech Startup',
		background: {
			type: 'gradient',
			solidColor: '#ffffff',
			gradientColors: ['#30cfd0', '#330867'], // Vibrant cyan to deep purple
			gradientDirection: 'to bottom right',
			noise: 0,
			borderRadius: 40,
			pattern: 'none',
			patternColor: '#000000',
			patternOpacity: 0.1,
			shape: 'squircle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-1',
				iconName: 'lucide:rocket',
				url: 'https://api.iconify.design/lucide/rocket.svg',
				x: 256,
				y: 256,
				scale: 1.2,
				rotation: 0,
				fill: 'none',
				stroke: '#ffffff',
				overwriteFill: false,
				overwriteStroke: true,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#30cfd0',
				shadowBlur: 15,
				shadowOffsetX: 0,
				shadowOffsetY: 0,
				shadowOpacity: 0,
			},
		],
	},
	{
		id: 'modern-abstract',
		name: 'Modern Abstract',
		background: {
			type: 'gradient',
			solidColor: '#000000',
			gradientColors: ['#240b36', '#c31432'],
			gradientDirection: 'to bottom right',
			noise: 0.1,
			borderRadius: 40,
			pattern: 'none',
			patternColor: '#000000',
			patternOpacity: 0.1,
			shape: 'rectangle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-3',
				iconName: 'lucide:hexagon',
				url: 'https://api.iconify.design/lucide/hexagon.svg',
				x: 256,
				y: 256,
				scale: 1.5,
				rotation: 0,
				fill: 'none',
				stroke: '#ffffff',
				overwriteFill: false,
				overwriteStroke: true,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#000000',
				shadowBlur: 0,
				shadowOffsetX: 0,
				shadowOffsetY: 0,
				shadowOpacity: 0,
			},
		],
	},
	{
		id: 'coffee-shop',
		name: 'Coffee Shop',
		background: {
			type: 'gradient',
			solidColor: '#3e2723',
			gradientColors: ['#3e2723', '#5d4037'], // Richer brown gradient
			gradientDirection: 'to bottom',
			noise: 0.1, // Added grain for texture
			borderRadius: 60,
			pattern: 'none',
			patternColor: '#000000',
			patternOpacity: 0.1,
			shape: 'rectangle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-coffee',
				iconName: 'lucide:coffee',
				url: 'https://api.iconify.design/lucide/coffee.svg',
				x: 256,
				y: 256,
				scale: 1.2,
				rotation: 0,
				fill: 'none',
				stroke: '#ffecb3', // Cream color for icon
				overwriteFill: false,
				overwriteStroke: true,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#000000',
				shadowBlur: 20,
				shadowOffsetX: 0,
				shadowOffsetY: 8,
				shadowOpacity: 0.6,
			},
		],
	},

	{
		id: 'music-studio',
		name: 'Music Studio',
		background: {
			type: 'gradient',
			solidColor: '#212121',
			gradientColors: ['#45e87a', '#3bf9d6'],
			gradientDirection: 'to top right',
			noise: 0,
			borderRadius: 30,
			pattern: 'none',
			patternColor: '#000000',
			patternOpacity: 0.1,
			shape: 'rectangle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-music',
				iconName: 'lucide:music',
				url: 'https://api.iconify.design/lucide/music.svg',
				x: 256,
				y: 256,
				scale: 1.2,
				rotation: 10,
				fill: '#ffffff',
				stroke: '#ffffff',
				overwriteFill: false,
				overwriteStroke: true,
				opacity: 0.9,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#000000',
				shadowBlur: 10,
				shadowOffsetX: 2,
				shadowOffsetY: 2,
				shadowOpacity: 0.5,
			},
		],
	},
	{
		id: 'gaming-clan',
		name: 'Gaming Clan',
		background: {
			type: 'gradient',
			solidColor: '#000000',
			gradientColors: ['#0f0c29', '#302b63', '#24243e'], // Deep purple night sky
			gradientDirection: 'to right',
			noise: 0,
			borderRadius: 0,
			pattern: 'none',
			patternColor: '#000000',
			patternOpacity: 0.1,
			shape: 'rectangle',
			radialCenterX: 50,
			radialCenterY: 50,
			radialRadius: 50,
		},
		layers: [
			{
				id: 'layer-gamepad',
				iconName: 'lucide:gamepad-2',
				url: 'https://api.iconify.design/lucide/gamepad-2.svg',
				x: 256,
				y: 256,
				scale: 1.5,
				rotation: 0,
				fill: '#00d2ff', // Neon cyan
				stroke: 'none',
				overwriteFill: true,
				overwriteStroke: false,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#00d2ff', // Glowing effect
				shadowBlur: 25,
				shadowOffsetX: 0,
				shadowOffsetY: 0,
				shadowOpacity: 0.7,
			},
		],
	},

	// NEW TEMPLATES
	{
		id: 'neon-radial',
		name: 'Neon Radial',
		background: {
			type: 'radial',
			solidColor: '#000000',
			gradientColors: ['#ff00cc', '#333399'],
			gradientDirection: 'to right',
			noise: 0,
			borderRadius: 40,
			pattern: 'none',
			patternColor: '#000000',
			patternOpacity: 0.1,
			shape: 'rectangle',
			radialCenterX: 30,
			radialCenterY: 30,
			radialRadius: 60,
		},
		layers: [
			{
				id: 'layer-neon',
				iconName: 'lucide:zap',
				url: 'https://api.iconify.design/lucide/zap.svg',
				x: 256,
				y: 256,
				scale: 1.3,
				rotation: 0,
				fill: 'none',
				stroke: '#ffffff',
				overwriteFill: false,
				overwriteStroke: true,
				opacity: 1,
				blendMode: 'normal',
				visible: true,
				locked: false,
				shadowColor: '#ff00cc',
				shadowBlur: 20,
				shadowOffsetX: 0,
				shadowOffsetY: 0,
				shadowOpacity: 0.8,
			},
		],
	},
];
